Task4With*
AlexMackevich/JIS7 pull request #3
Opened 2021-05-27 05:13 UTC by AlexMackevich

2021-05-27 12:16 UTC, KaydunovDenis requested changes
See my comment

2021-05-27 12:16 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/ForthExampleFromArtemiy/App.java
> +
There are a lot of unnecessary empty lines

2021-05-27 12:16 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/ForthExampleFromArtemiy/App.java
> +        persons.add(person6);
If you use java version 11+, then you can use this construction:
Product product = new Product("BubbleGum", 2.50, 2.0);
Product product2 = new Product("Lays", 3.20, 50.0);
Product product3 = new Product("Milk", 1.50, 0.0);
.... и т.д.
List listProduct = new ArrayList<>(){
add(product);
add(product1);
add(product)2;
.... и т.д.
}

2021-05-27 12:16 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/ForthExampleFromArtemiy/Model/Person.java
> +
empty lines

2021-05-27 12:16 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/ForthExampleFromArtemiy/Model/Skill.java
> +
empty lines

2021-05-27 12:16 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/ForthExampleFromArtemiy/Service/PersonServiceImpl.java
> +
А вторая часть задания?

Если не найден никто с подходящим процентом, тов вернуть человека с максимальным  уровнем навыка из имеющихся Person

2021-06-12 18:48 UTC, ArtikTico approved these changes
Good job

2021-06-12 18:49 UTC, merged