Task5
AlexMackevich/JIS7 pull request #4
Opened 2021-06-02 06:45 UTC by AlexMackevich

2021-06-03 12:54 UTC, KaydunovDenis requested changes

2021-06-03 12:54 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/src/main/java/App.java
> +        productList. add(cognac);
This can be extracted into a separate method

2021-06-03 12:54 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/src/main/java/App.java
> +    }
This can be extracted into a separate method.
You can use the construction:
Comporator.comparing(......).thenComparing(....).thenComparing(....)

2021-06-03 12:54 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/src/main/java/Repository/RepositoryOfProducts.java
> +    List<Product> listOfProducts = new ArrayList<>();
private or public?

2021-06-03 12:54 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/src/main/java/Repository/RepositoryOfProducts.java
> +    }
You can extracte metode 
public void initialListProduct(){}

2021-06-03 12:54 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/src/main/java/Service/ProductService.java
> +}
А вот это + ProductServiceImpl  круто. Нужно будет тоже так писать.

2021-06-03 12:54 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/src/main/java/Service/ProductServiceImpl.java
> +    public void findProductWithLowPriceAndHighDiscount(List<Product> productList) {
Задание гласило:
"3.в. Найти самый дешевый продукт с самой большой скидкой"

по логике твой  метод должен быть 
public **Product** findProductWithLowPriceAndHighDiscount(List<Product> productList)

Совсем не понял откуда ты взял average. В заданиях нигде не было "найти среднее значение"

2021-06-03 12:54 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/src/main/java/Service/ProductServiceImpl.java
> +    double averageDiscountOnProducts;
Совсем не понял откуда ты взял average. В заданиях нигде не было "найти среднее значение"

2021-06-03 12:54 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/src/main/java/Service/ProductServiceImpl.java
> +    public void findProductWithHighPriceAndLowDiscount(List<Product> productList) {
по логике твой метод должен быть
public Product findProduct...........

2021-06-05 06:48 UTC, ArtikTico reviewed
Чекай комменты

2021-06-05 06:48 UTC, ArtikTico commented on LamdasAndStreams/src/main/java/src/main/java/App.java
> +        productList. add(cognac);
пробел между productList. и add не нужен. А так в принципе норм. Для демонстрации сойдет. Можно конечно и в отдельный методы как Денис советуета тут вызывать метод который инициализирует тестовые данные

2021-06-05 06:48 UTC, ArtikTico commented on LamdasAndStreams/src/main/java/src/main/java/App.java
> +                .sorted(Comparator.comparing(Product::getDiscountOnProduct))
тут нет необходимости юзать 2 раза метод sorted . Тем более что в одном случае ты`лямбдой` это делаешь а второй случай `метод референс`.
Тут Денис прав можно в одном компараторе это заюзать

2021-06-05 06:48 UTC, ArtikTico commented on LamdasAndStreams/src/main/java/src/main/java/Service/ProductServiceImpl.java
> +    double averageDiscountOnProducts;
так лучше не делай.
В сервисе не ужно заводить меременные для хранения результата прохода стрима. ты можешь вернуть это в методе и в месте вызова метода результат присвоить переменной

2021-06-09 18:18 UTC, KaydunovDenis commented
@AlexMackevich по-моему ты в гит запушил файлы .class   их в гит игнор, а вообще они должны были быть в target, а target в .gitignore

2021-06-12 18:50 UTC, ArtikTico approved these changes
good

2021-06-12 18:51 UTC, merged