Changed Task4
AlexMackevich/JIS7 pull request #5
Opened 2021-06-03 08:26 UTC by AlexMackevich

2021-06-03 13:25 UTC, KaydunovDenis requested changes

2021-06-03 13:25 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/Task4/Repository/Repository.java
> +    public void addPersonsToListOfPersons(){
Replace name's method as
public void initialListOfPerson()

2021-06-03 13:25 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/Task4/Repository/Repository.java
> +public class Repository {
Replace name's class  as 
public class PersonsRepository

2021-06-03 13:25 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/Task4/Repository/Repository.java
> +            new Skill("Hindi", 40));
объекты класса Person зачем делать static?
Можно все извлечь в отдельный метод initialRepository()

есть такая конструкция упрощенная
public static final List<Person> listOfPersons = new ArrayList<>{{
add(new Person(.........................));
add(new Person(.........................));
add(new Person(.........................));
add(new Person(.........................));
add(new Person(.........................));
}}

2021-06-05 06:42 UTC, ArtikTico approved these changes
Чекай комменты. Я смержу но почитай

2021-06-05 06:42 UTC, ArtikTico commented on LamdasAndStreams/src/main/java/Task4/Repository/Repository.java
> +public class Repository {
Тогда уже `PersonRepository` а не PersonsRepository - мы не называем классы сервисы и репозитории во множественном числе

2021-06-05 06:42 UTC, ArtikTico commented on LamdasAndStreams/src/main/java/Task4/Repository/Repository.java
> +    public void addPersonsToListOfPersons(){
`addPersonsToListOfPersons()` - > `initPersonList`

2021-06-05 06:42 UTC, merged

2021-06-09 17:34 UTC, KaydunovDenis commented on LamdasAndStreams/src/main/java/Task4/Repository/Repository.java
> +public class Repository {
@ArtikTico Ревьювать чужой код, даже полезнее чем писать самому)) Словно учусь на чужих ошибках)